### PR TITLE
use cdnjs links for external assets

### LINKED ISSUE #10: Need update to subdependencies bootstrap and jquery
Hi visjs team,

I have gotten to this page from being referred to by @mojoaxel  who I found through your github page. I am filing an issue to update some of vis-network’s subdependencies.  The ones in particular are bootstrap and jquery.  Our risk team here at paypal has deemed these versions of the libraries you guys are utilizing to be potentially vulnerable and are not allowing them to pass the ECI check scripts.  Please advise on how I can raise the version of bootstrap to 3.4.1 or higher and having at least the latest version of jquery 1.x.x or 2.x.x.  Please and thank you for your time.  Please see the attached screenshot for reference.  Thanks again!
browser: chrome(not a frontend issue so not relevant in my opinion)
This screenshot reveals visjs(4.21.0) but when I tried it with vis-network(5.0.0) it was utilizing the same versions of these libraries.
Screen Shot 2019-07-23 at 8 31 24 PM
 
Best Regards,

Joseph Kwon

### PR DESCRIPTION
**Pull request by mojoaxel**
this partially fixes #10

### CODE REVIEW

**Comment by mojoaxel** [comment]
This is still a DRAFT. Please do not merge!
We need to figure out what to do with `propagating-hammerjs` first.

**Comment by Thomaash** [comment]
`propagating-hammerjs` has less than 200 lines of code and only a single function. Maybe we can copy it to vis-util and maintain there?

**Comment by Thomaash** [comment]
It's MIT so there should be no licencing issues.

**Comment by Thomaash** [comment]
I removed `propagating-hammerjs` and everything seems to work the same (at least on the devices I have available at the moment):
- [x] test,
- [x] build,
- [x] Chromium (Linux),
- [x] Firefox (Linux),
- [x] Gnome Web (Linux),
- [x] Chrome (Android Marshmallow),
- [x] Chrome (Android KitKat),
- [x] Opera (Android KitKat),
- [x] Safari (3rd generation iPad),
- [x] built-in browser (Android Oreo TV): on screen buttons didn't work with and don't work without.

I just can't find any difference, we probably don't need it at all.

**Comment by mojoaxel** [comment]
Maybe @josdejong can write one or two sentence on why `propagating-hammerjs` was created and if it's still needed?? :wave:

**Comment by mojoaxel** [comment]
I removed `propagating-hammerjs`and could not see any problem with `examples/network/events/interactionEvents.html`.

Feel free to merge!

**Pull request merged**
