### PR TITLE
chore(examples): fix broken script paths

### PR DESCRIPTION
**Pull request by Thomaash**
Some paths in the examples pointed to nonexistent files. This fixes that.

### CODE REVIEW

**Comment by Qix-** [comment]
Doesn't seem to be fixed on the site.

**Comment by Thomaash** [comment]
This is fixed, this however affected only two examples.

**Comment by Qix-** [comment]
image

**Comment by Thomaash** [comment]
I know but I'm 99.99 % sure this is a different issue.

**Pull request merged**
