### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by Thomaash**
I played around a bit with Travis in one of my projects and thought it would be neat to have it here.

- Runs `npm test` on each commit and pull request.
- On each commit to (merge into) master it publishes to npmjs (uses `@next` tag and each version includes commit hash, `@latest` and normal versions are still handled manually to prevent random errors in production).

Of course someone has to fill in email, access token (who will be credited with the releases on npmjs), create Travis account and enable this project.

PS: The publishing part can be disabled.

### CODE REVIEW

**Comment by mojoaxel** [comment]
:+1: This is a nice and necessary step into the direction of automatic releases (#1)

**Comment by mojoaxel** [comment]
> Of course someone has to fill in email, access token (who will be credited with the releases on npmjs), create Travis account and enable this project.

I think this is the moment you become one of the official maintainers of this project if @yotamberk is OK with it :tada: You already should have access rights :smile: 

Feel free to enable Travis for this project after this PR is merged.

**Comment by Thomaash** [comment]
Okay, I'll take care of it. One more thing though, for the publishing part to work I need access to npmjs.

**Comment by mojoaxel** [comment]
> Okay, I'll take care of it. One more thing though, for the publishing part to work I need access to npmjs.

Done. You are member of the org [visjs](https://www.npmjs.com/org/visjs) and the teams `network` and `developers`.

**Comment by Thomaash** [comment]
Thanks, I'll set it up.

**Comment by Thomaash** [comment]
This is now ready for review/merge.

**Comment by mojoaxel** [comment]
@Thomaash Why did you close this? Can we not merge it?

**Comment by Thomaash** [comment]
My Travis stopped working and I spend 2 days trying to fix it in vain.
However I tried CircleCI yesterday and it works and looks much more
flexible. Today or tommorrow I'll open a new PR (if nothing goes wrong
again).

**Pull request closed without merging**
