### PR TITLE
fix: handle dragging of non-selected nodes

### LINKED ISSUE #1596: After dragging a non-selected node you can no longer drag the selected node
This issue is reproducible on the basic usage example https://visjs.github.io/vis-network/examples/network/basicUsage.html

Steps:

1. Click on `Node 1` to select it
2. Drag `Node 2` 
3. Try to drag `Node 1`.
    - The entire canvas starts to pan

I tried to work around this by hooking into the `dragStart` and `dragEnd` events to see if I could programatically unselect/resleect the originally selected node, however, in both events `Node 2` is passed as the selected node even though `Node 1` has the selected node styling

### PR DESCRIPTION
**Pull request by tkolanko**
When starting a drag keep track of the currently selected nodes.
When the drag is complete automatically re-select them.

Closes #1596.

### CODE REVIEW

**Comment by tkolanko** [comment]
@Thomaash any chance you can review this?

**Comment by micrology** [comment]
Could this be reviewed?  My users have been complaining about the bug.  Thanks.

**Comment by tkolanko** [comment]
@Thomaash anything I can do to get this PR merged in?

**Comment by micrology** [comment]
This PR has been waiting for review for two months now...

**Comment by nickchomey** [comment]
Any chance this can be merged? I see this as well

**Comment by Thomaash** [comment]
> Any chance this can be merged? I see this as well

No. This doesn't solve the problem. The code clearly says unselect everything and select the dragged node, that's what doesn't happen, that's where the problem is and that's what should be fixed. This PR doesn't even touch this part, it dances around it to (presumably, I wan't able to get this branch to run on my machine at all) make this particular symptom disappear.

**Pull request closed without merging**
