### PR TITLE
chore(test): added visual regression tests

### LINKED ISSUE #33: create automated regression tests
We should introduce screenshot/regression tests!
I would recommend https://www.cypress.io

### PR DESCRIPTION
**Pull request by mojoaxel**
fixes #33

### CODE REVIEW

**Comment by Thomaash** [comment]
Oh, I have to start the server manually.

**Comment by Thomaash** [comment]
Are you sure the nodes are always placed exactly the same? All the tests fail for me with what seems as slight misalignment of nodes.

**Comment by Thomaash** [comment]
nodeStyles - HTMLInNodes -- match screenshot diff

**Comment by mojoaxel** [comment]
> Are you sure the nodes are always placed exactly the same? All the tests fail for me with what seems as slight misalignment of nodes.

Oh no!
@Thomaash  can you please try `npm run test:cypress`

**Comment by mojoaxel** [comment]
> Oh, I have to start the server manually

Yeah :disappointed: We need a solution for this...

**Comment by Thomaash** [comment]
Try this: examples/network/layout/randomSeed.html .

**Comment by Thomaash** [comment]
If it works we could simple set all the examples the same way. Or maybe all but one to show the default behavior.

**Comment by Thomaash** [comment]
Pulled the recent changes: 12/12 fail.

**Comment by mojoaxel** [comment]
> All the tests fail for me with what seems as slight misalignment of nodes.

Yes the rendering depends on the browser and the OS, installed fonts... :disappointed: 
Even if we are not able to fix this we maybe still could use it from inside Travis because it has a reliable environment!?

**Comment by Thomaash** [comment]
We can fix the environment to specific version so it should work.

**Comment by Thomaash** [comment]
We can ship some default fonts, use hardcoded seed in the examples. AFAIK Cypress packs it's own electron so even this should be consistent (hopefully) if we pin a specific version.

**Comment by mojoaxel** [comment]
The tests are all broken ATM because of #60

**Comment by mojoaxel** [comment]
closing in favor of #187 :tada:

**Comment by Thomaash** [comment]
#187 doesn't replace this, it actually complements this. It would be best to have both.

**Pull request closed without merging**
