### PR TITLE
fix: add label prop to ctxRenderer

### PR DESCRIPTION
**Pull request by yotamberk**
When trying to add a custom shape via the `ctxRenderer` prop for nodes, sometimes the label is useful to inject in the custom shape itself.
I've added this so it's very easy to use.
Except for this addition, when adding a custom shape, the label is drawn below and this is unwanted so I returned straight after a custom shape is drawn.

### CODE REVIEW

**Comment by Thomaash** [comment]
@yotamberk 

Rethinking this, wouldn't it be better to return further instructions from the function? Something like:
```typescript
interface CtxRendererReturnValue {
  renderLabel: boolean;
}
```

This way we would avoid breaking changes (`renderLabel` property would default to `true`) and also people, who just want to put custom shape above the label, could render the shape and have standard node label for free.

**Comment by yotamberk** [comment]
makes sense. I'll fix it now and resubmit

**Comment by Thomaash** [comment]
Okay, I stopped the release in CI.

**Comment by yotamberk** [comment]
I can maybe add another prop simply with the `renderLabel: boolean;` that defaults to `true`

**Comment by Thomaash** [comment]
Do we actually know where to render the label? Because custom shape can be anything of any size. Maybe we should just skip the label altogether after all.

**Comment by yotamberk** [comment]
Rethinking this, in order of doing this, we wil need to add a prop to the nodes options. I don;t think we want to do this. The original PR is what I intended

**Comment by yotamberk** [comment]
Can we revert the revert?

**Comment by Thomaash** [comment]
Yeah, I agree. It will be best to skip the label and let people deal with it (i.e. custom means custom).

**Comment by Thomaash** [comment]
Revert reverted :smile:

**Comment by yotamberk** [comment]
Thanks 😄

**Comment by yotamberk** [comment]
We just need to make sure the CI runs again so it publishes properly

**Comment by Thomaash** [comment]
This should be fine. I canceled the previous runs before they got to releasing so the last one should release as if the reverts didn't even happen.

**Pull request merged**
